### ISSUE TITLE
Adding a table of golf scores by language / by day

### ISSUE THREAD

**Issue by PPKFS** [Starwort/advent-of-golf-2022#21]
It would be kind of neat to see a table of scores on the main readme. I think because markdown tables are a headache to work with raw, I'm sure there must exist a way to generate one from a yaml file and amend it to the readme.

That way, it would only need people to add a single (yaml) line to a file with their character count, rather than a new line of a table.

It could also encourage more people to try golfing the existing solutions :)

**Comment by Starwort** [comment]
Markdown tables actually aren't that nasty to work with; I think that this is a very good idea. I'll go ahead and add a table to the main README now.

**Comment by PPKFS** [comment]
Oh, that is excellent. Thank you!

**Comment by Starwort** [comment]
Closed by [0426987](https://github.com/starwort/advent-of-golf-2022/commit/04269873472eb02ac5382fe1b73f86a42f6e8ec6)
